# #####################################################################
# Automatically generated by qmake (2.01a) niedz. kwi 12 14:38:12 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    lista.cpp
HEADERS += lista.h
