# #####################################################################
# Automatically generated by qmake (2.01a) czw. kwi 9 22:26:51 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    book.cpp
HEADERS += book.h
